### ISSUE TITLE
Auto lobby

### ISSUE THREAD

**Issue by Michaelmvv** [palechip/HudPixel#101]
Im not sure if this is intended or not, but in CvC games the auto /lobby does not work. 
If you would like to know, the lobby confirm message for CvC is "Are you sure? In Cops and Crims you respawn next round! Type /lobby again if you really want to quit."

**Comment by palechip** [comment]
It wasn't intended to be that way. But I guess it makes sence to leave it that way. I don't really want to encourage leaving CvC. On the other hand it's the players decision.

I guess I'll think about it for a while.

**Comment by Michaelmvv** [comment]
Not Needed.
