### ISSUE TITLE
Tip all button recommendation. 

### ISSUE THREAD

**Issue by Michaelmvv** [palechip/HudPixel#45]
Because Hypixel has disabled "/tip all" I think you should rename the button to "Tip" and it would tip for the game you where playing. so if you are playing BSG and you click tip it tips whoever activated the booster for BSG. I am sure this is allowed because the server itself puts clickable text into chat that does this .

**Comment by palechip** [comment]
This couldn't replace the tip-all button but it is a reasonable addition.
As far as I'm aware /tip-all isn't gone forever but it'll take quite some time to come back. (About the time when their ecomomy revamp comes is my estimate)

**Comment by palechip** [comment]
I'd rather not add this feature because you simply can click the text at the start and at the end. There is no need to tip during the game.

Thanks anyway!
