### ISSUE TITLE
Namechanges let the Boosters part bug out

### ISSUE THREAD

**Issue by MyzelYam** [palechip/HudPixel#46]
Just noticed that some names in "Boosters" are old ones. It would be awesome, if you add namechange support!
Thanks for reading, have a nice day!

**Comment by palechip** [comment]
I'll look into it. The mod already is able to handle the UUID -> Name conversion. However I didn't expect the code used to break with name changes since it originates in the realms library used by Minecraft...

**Comment by MyzelYam** [comment]
Thanks much love man <3
