### ISSUE TITLE
Mage optimal range

### ISSUE THREAD

**Issue by Michaelmvv** [palechip/HudPixel#59]
I think a nice feature would be an optimal range notifier when playing the mage class. If the player is a Pyromancer it would warn them if the block they are looking at was more than 50 blocks away. If the player is a Cryomancer it would would warn them if the block they where looking at was more than 30 blocks away, and if they are a Aquamancer it would warn them if they were more than 40 blocks away.

**Comment by palechip** [comment]
It would certainly be a cool feature but I won't add it because I think it gives you too much of an advantage. Also it would only confuse players who don't know the mechanics as well as we do.
