### ISSUE TITLE
TKR timer starts too early.

### ISSUE THREAD

**Issue by Cooltimmetje** [palechip/HudPixel#88]
Just like the title says, it starts before the race it self actually started. (When you get teleported to the track, the timer starts counting)

**Comment by palechip** [comment]
Hypixel is also starting its timer it this moment. You can verify this by checking the time when completing the first lap. There should be a ~12 second difference if the official timer started when the actual race started.

Even if Hypixel corrects this behavior the timer won't break. The main timer corrects it's time after the first lap by using the official time. And if there is a difference it will also take this difference into account for future games in the same session.

https://github.com/palechip/HudPixel/blob/cc81963e9ab6f75c3f17ad95a14a6cebf3c9248c/src/main/java/com/palechip/hudpixelmod/components/TkrTimer.java#L103-L108

**Comment by Cooltimmetje** [comment]
Oh ok! Never noticed that. But thanks for explaining it :)
