### ISSUE TITLE
Quick Load never shows TNTGames boosters

### ISSUE THREAD

**Issue by MyzelYam** [palechip/HudPixel#91]
When pressing Quick Load and a TNTGames booster is active it hides/doesn't show TNTGames boosters. Looks like you forgot something there. To reproduce just press Quick Load and compare the result with the /booser queue command result.

**Comment by palechip** [comment]
The problem is, that the booster queue is listing them as `TNTGames`. ButHudPixel only looks for `TNT Games` or The `TNT Games`. However this is easily fixable with HudPixelUpToDate. Once I catch a TNT Games booster (hopefully later today), I'll verify the fix and push it.
